# This is a basic workflow to help you get started with Actions

name: debCreate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir -p aacs-updater/DEBIAN aacs-updater/opt/aacs-updater aacs-updater/systemd/system
          cp *.timer aacs-updater/systemd/system/
          cp aacs-updater.sh aacs-updater/opt/aacs-updater/
          echo "Name: aacs-updater\nVersion: 0.1\nArchitecture: amd64\nDepends: wget (>=1.21), unzip (>= 6.00)\nMaintainer: RiderExMachina <riderexmachina@protonmail.com>\nDescription: A program that updates the BluRay AACS on a weekly basis." >> aacs-updater/DEBIAN/control
          echo "deb-systemd-helper enable aacs-updater.timer" >> aacs-updater/DEBIAN/postinst
          dpkg-deb aacs-updater
